---
title: "2/22/2023"
output: html_notebook
---

```{r}
library(tidyverse)
library(ISLR2)
library(MASS) # for LDA and QDA regressions
```

# LDA Performance with Synthetic 1D data

Generate the mixture model data:

```{r}
set.seed(100) # set seed for reproducibility
# defines and the standard devs of the two Gaussians
mu <- c(-1, 2)
sigma <- c(1., 1.)
# prior probabilities
prior <- c(0.3, 0.7)

# number of total samples we draw from the mixture model
n = 10^6

# first sample the class varaible n times
class<- sample(1:2,n,replace = TRUE, prob = prior)
# convert to categorical variable
class <- as.factor(class)
# sample the x values (what we measure in practice)
# preallocates the array
x <- numeric(n)
for(j in 1:n){
  # sample Gaussian 1 or Gaussian 2 as appropriate
  x[j] <- rnorm(1,mean = mu[class[j]], sd = sigma[class[j]])
}
# store as a tibble
mixture.df <- tibble("class"=class, "x"=x)

```

Train classifiers

```{r}
lda.fit <- lda(class~x, data = mixture.df)
logistic.fit <- glm(class~x,data=mixture.df, family = binomial)
```

Check error rates

```{r}
pred.train <- predict(lda.fit)
mean(pred.train$class != mixture.df$class)
table(pred.train$class, mixture.df$class)

```

```{r}
logistic.prob <- predict(logistic.fit, type = "response")
logistic.pred<- rep(1, nrow(mixture.df))
logistic.pred[logistic.prob>0.5] <-2
mean(logistic.pred != mixture.df$class)
table(logistic.pred, mixture.df$class)

```
